### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hutaohutc** [rubenarslan/formr#21]
When I run `devtools::install_github("rubenarslan/formr")`, I got following errors:
```
* installing *source* package 'formr' ...
** R
Error : (converted from warning) unable to re-encode 'feedback_plotting.R' lines 156, 243, 296, 319
ERROR: unable to collate and parse R files for package 'formr'
* removing 'C:/Users/hutao/F/R/R-3.5.2/library/formr'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/hutao/AppData/Local/Temp/RtmpYpwBYO/file21b44f523041/formr_0.8.3.tar.gz’ had non-zero exit status
```

**Comment by xiangrong2233** [comment]
I meet the same issue.

**Comment by rubenarslan** [comment]
Sorry, I cannot reproduce the error. From googling, it seems like it could happen if you have a bad connection?

Either way, I also just updated the package for unrelated reasons. Can you try installing again and let me know how it goes? If it still doesn't work can, you send me the output of `devtools::session_info()`?

**Comment by xiangrong2233** [comment]
I didn't find out what the problem is, but I change the R to 3.4.4,  and then everthing is ok.






------------------ 原始邮件 ------------------
发件人: "Ruben C. Arslan"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 下午5:35
收件人: "rubenarslan/formr"<formr@noreply.github.com>;
抄送: "RouJI"<1730858284@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [rubenarslan/formr] install error (#21)




Sorry, I cannot reproduce the error. From googling, it seems like it could happen if you have a bad connection?
 
Either way, I also just updated the package for unrelated reasons. Can you try installing again and let me know how it goes? If it still doesn't work can, you send me the output of devtools::session_info()?
