### ISSUE TITLE
Not working anymore: formr_results()

### ISSUE THREAD

**Issue by adrian-gadient** [rubenarslan/formr#26]
Last Friday I last downloaded data from a current survey using `formr_results()`. The same code doesn't work anymore since yesterday. I get the following error message:
```

Error in formr_item_displays(survey_name, host) : 
  object 'results' not found
In addition: Warning message:
In formr_item_displays(survey_name, host) :
  This item display table for this survey could not be accessed.
```

Any ideas what I could do to make the function work again?

(Using `formr_raw_results()` and `formr_post_process_results()`work, by the way.)

**Comment by rubenarslan** [comment]
Hi @abruegger. We disabled exporting the item display table, because we're experiencing very high server load because of multiple ongoing corona studies and these exports are expensive operations and can block data collection. Sorry, we'll turn it on again, when the load goes down or we find a way not to block data collection during export.

**Comment by adrian-gadient** [comment]
Thanks Ruben. Very understandable. I was just confused and wondered what was happening. Is there some website where you inform users about such changes or a mailing list with important updates? That would be great in such circumstances. 
Thanks again for your great work on formR and Codebook!
Adrian
