### ISSUE TITLE
Offline capability

### ISSUE THREAD

**Issue by smuyengwa79** [rubenarslan/formr#36]
Is there a specific timeline for formr to be able to collect data offline?

**Comment by rubenarslan** [comment]
No, but we'd welcome a pull request along these lines or it could be an item to specify consulting with respect to this feature in a grant. 

The best open source form solution that does offline well in my opinion are the ODK clients, especially [enketo](https://enketo.org/).

**Comment by smuyengwa79** [comment]
I was reading the paper published on formr and it mentions offline capability as one of the functionalities that were to be added. I agree with those tools you suggest but setting up longitudinal surveys looks more straight forward with formr compared to the other softwares. The grant route could be an option to explore provide we know what resources are required

**Comment by rubenarslan** [comment]
I agree that formr is more straightforward for longitudinal data collection than ODK. Also, ODK usually proceeds from the assumption that there's an interviewer collecting multiple interviews IIRC. That said, you could design offline surveys in enketo and use formr to schedule assessments (how you get the pings to do the survey to the user without connectivity is another question though, e.g. text messages still require cellular coverage).

Offline capability is on my radar, but because mobile data coverage has improved a lot around here, it's dropped in the priority list. However, I hope to start work on a progressive web app with push notifications for formr. Offline capability would be easier to add once that is done. The bottleneck is Cyril's and my time, a line item in a grant would allow us to recruit others to pitch in.

Feel free to write me an email if you are in the considering options stage and I can potentially help if I better understand your plans.
